### ISSUE TITLE
Sample Dataset

### ISSUE THREAD

**Issue by spmallick** [opencv-ai/superannotate#1]
It would be nice for users to have an option of sample dataset to get started. This should not be part of package itself, but one that quickly downloads on demand.

**Comment by vahansa** [comment]
I added an example project in the repo. You can open by clicking 'open project' in the start menu, then choose the path to the project. 
<img width="507" alt="Open Example Project" src="https://user-images.githubusercontent.com/60094888/94257787-e5fe7280-ff3c-11ea-987b-19a55ba5212f.png">

**Comment by spmallick** [comment]
Great. Thank you!
