### ISSUE TITLE
how to export xml files its creating json?

### ISSUE THREAD

**Issue by Umar-Iftikhar** [opencv-ai/superannotate#3]

**Comment by rcmanga** [comment]
Our [Python SDK](https://superannotate.readthedocs.io/en/latest/index.html) provides [annotation format converters](https://superannotate.readthedocs.io/en/latest/superannotate.sdk.html#converting-annotation-format-to-and-from-superannotate-format) between Superannotate and other common formats e.g COCO, Pascal VOC.  If you need custom conversion to xmls, other then provided conversion formats please refer to [Superannotat's export format documentation](https://github.com/opencv-ai/superannotate#export).

**Comment by Petros626** [comment]
@Umar-Iftikhar able to solve this?
